apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-admin-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-admin-frontend-app
  template:
    metadata:
      labels:
        app: e-admin-frontend-app
    spec:
      containers:
      - name: e-admin-frontend-app
        image: webapp:1
        ports:
        - containerPort: 4200
        resources:
           limits:
             memory: 500Mi
             cpu: 250m
           requests:
             memory: 100Mi
             cpu: 125m
      dnsPolicy: Default  

---
apiVersion: v1
kind: Service
metadata:
  name: e-admin-frontend-service-cip
  labels:
    app: e-admin-frontend-app
spec:
  type: ClusterIP
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 4200
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: e-admin-frontend-app      
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: e-admin-frontend-service
#   labels:
#     app: e-admin-frontend-service
# spec:
#   type: NodePort
#   ports:
#     # the port that this service should serve on
#     - port: 80
#       targetPort: 8025
#   # label keys and values that must match in order to receive traffic for this service
#   selector:
#     app: e-admin-frontend-app

# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: e-admin-frontend-ingress
# spec:
#   rules:
#   - host: e-admin-frontend-app.cluster-ingress-subdomain
#     http:
#       paths:
#       - backend:
#           serviceName: e-admin-frontend-service-cip
#           servicePort: 80
#         path: /
#   tls:
#   - hosts:
#     - e-admin-frontend-app.cluster-ingress-subdomain
#     secretName: cluster-ingress-secret